import AuthProvider from "@/Providers/AuthProvider";
import Sidebar from "@/components/Sidebar/Sidebar";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function DashboardLayout({ children }) {
  return (
    <>
      <AuthProvider>
        <div className="flex flex-row">
        <div className='w-[15%]  shadow  min-h-[100vh] '>
        <Sidebar/>
        </div>
          <div className="w-[80%]  px-[50px]  py-[50px]">{children}</div>
        </div>
      </AuthProvider>
    </>
  );
}
