import AuthProvider from "@/Providers/AuthProvider";
import Sidebar from "@/components/Sidebar/Sidebar";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <>
      {/* <AuthProvider> */}
        <div className="flex flex-row">
          <Sidebar />
          <div>{children}</div>
        </div>
      {/* </AuthProvider> */}
    </>
  );
}
