import AuthProvider from "@/Providers/AuthProvider";
import Navbar from "@/components/Navbar/Navbar";
import Sidebar from "@/components/Sidebar/Sidebar";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function DashboardLayout({ children }) {
  return (
    <>
      <AuthProvider>
        <div className="flex flex-row">
          <Sidebar />
          <div className="w-[85%] max-[1200px]:w-[100%] box-border">
            <Navbar />
            <div className=" p-[50px] max-[1200px]:p-[10px]">{children}</div>
          </div>
        </div>
      </AuthProvider>
    </>
  );
}
